name: Build and Test Java
on:
  pull_request:
    branches: ["main"]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17']
    name: Java ${{ matrix.java }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Check formatting
        run: ./gradlew spotlessCheck --no-daemon

      - name: Build and test
        run: ./gradlew build --no-daemon
